import { useState } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, CheckCircle, Youtube, Link2, Clock } from "lucide-react";

function extractVideoId(url: string): string | null {
  const regex =
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/|youtube\.com\/shorts\/)([^&\n?#]+)/;
  const match = url.match(regex);
  return match ? match[1] : null;
}

function generateHTMLContent(
  videoId: string,
  redirectUrl: string,
  triggerTime: number
) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Redirect After YouTube Ends</title>
  <style>
    html, body {height:100%;margin:0;}
    #player {position:fixed;inset:0;width:100%;height:100%;border:0;background:#000;}
  </style>
</head>
<body>
  <div id="player"></div>
  <script src="https://www.youtube.com/iframe_api"><\/script>
  <script>
    const VIDEO_ID   = "${videoId}";
    const TARGET_URL = "${redirectUrl}";
    const TRIGGER_AT    = ${triggerTime};
    const POLL_INTERVAL = 250;
    let pollId = null, player;

    function onYouTubeIframeAPIReady() {
      player = new YT.Player("player", {
        videoId: VIDEO_ID,
        playerVars: {
          autoplay: 1,
          mute: 1,
          rel: 0,
          playsinline: 1,
          enablejsapi: 1
        },
        events: {
          onStateChange: handleStateChange
        }
      });
    }

    function handleStateChange(event) {
      if (event.data === YT.PlayerState.PLAYING) {
        pollId = setInterval(() => {
          const currentTime = player.getCurrentTime();
          if (currentTime >= TRIGGER_AT) {
            clearInterval(pollId);
            window.location.href = TARGET_URL;
          }
        }, POLL_INTERVAL);
      } else if (event.data === YT.PlayerState.ENDED) {
        clearInterval(pollId);
        window.location.href = TARGET_URL;
      } else {
        clearInterval(pollId);
      }
    }
  <\/script>
</body>
</html>`;
}

function generateReadme(
  youtubeUrl: string,
  redirectUrl: string,
  triggerTime: number
) {
  return `# YouTube Redirect Page

This page automatically redirects users after a YouTube video ends or reaches a specified time.

## Configuration
- **YouTube Video**: ${youtubeUrl}
- **Redirect URL**: ${redirectUrl}
- **Trigger Time**: ${triggerTime} seconds

## Installation
1. Upload the \`index.html\` file to your web server
2. Access the page via your website URL
3. The video will play automatically and redirect users when complete

## Notes
- The video starts muted to comply with browser autoplay policies
- Users can unmute the video if desired
- The redirect happens at ${triggerTime} seconds OR when the video ends (whichever comes first)

Generated by YouTube Redirect Page Generator
`;
}

export default function YoutubeRedirect() {
  const [youtubeUrl, setYoutubeUrl] = useState("");
  const [redirectUrl, setRedirectUrl] = useState("");
  const [triggerTime, setTriggerTime] = useState(32);
  const [generated, setGenerated] = useState(false);
  const [error, setError] = useState("");

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    const videoId = extractVideoId(youtubeUrl);
    if (!videoId) {
      setError("Please enter a valid YouTube URL");
      return;
    }

    setGenerated(true);
  };

  const handleDownload = async () => {
    const videoId = extractVideoId(youtubeUrl);
    if (!videoId) return;

    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();

    zip.file(
      "index.html",
      generateHTMLContent(videoId, redirectUrl, triggerTime)
    );
    zip.file(
      "README.md",
      generateReadme(youtubeUrl, redirectUrl, triggerTime)
    );

    const content = await zip.generateAsync({ type: "blob" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(content);
    link.download = "youtube-redirect-page.zip";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <main className="min-h-screen py-24 md:py-32 px-4 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-card/15 to-transparent pointer-events-none" />

      <div className="container mx-auto max-w-xl relative">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-3xl md:text-4xl font-bold mb-3 text-center text-gradient-sunset">
            YouTube Redirect Page Generator
          </h1>
          <p className="text-muted-foreground text-center mb-10 max-w-md mx-auto">
            Generate a self-contained HTML page that plays a YouTube video and
            redirects users at a specific time.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.15 }}
        >
          <Card className="bg-card/60 backdrop-blur-sm border-white/[0.08]">
            <CardHeader>
              <CardTitle className="text-lg">Configuration</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleGenerate} className="space-y-5">
                <div className="space-y-2">
                  <Label
                    htmlFor="youtubeUrl"
                    className="flex items-center gap-2"
                  >
                    <Youtube className="h-4 w-4 text-red-500" />
                    YouTube Video URL
                  </Label>
                  <Input
                    id="youtubeUrl"
                    type="url"
                    required
                    placeholder="https://www.youtube.com/watch?v=VIDEO_ID"
                    value={youtubeUrl}
                    onChange={(e) => {
                      setYoutubeUrl(e.target.value);
                      setGenerated(false);
                    }}
                    className="bg-background/50"
                  />
                  <p className="text-xs text-muted-foreground">
                    Paste the full YouTube video URL
                  </p>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="redirectUrl"
                    className="flex items-center gap-2"
                  >
                    <Link2 className="h-4 w-4 text-blue-400" />
                    Redirect URL
                  </Label>
                  <Input
                    id="redirectUrl"
                    type="url"
                    required
                    placeholder="https://your-website.com/target-page"
                    value={redirectUrl}
                    onChange={(e) => {
                      setRedirectUrl(e.target.value);
                      setGenerated(false);
                    }}
                    className="bg-background/50"
                  />
                  <p className="text-xs text-muted-foreground">
                    Where users should be redirected after the video
                  </p>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="triggerTime"
                    className="flex items-center gap-2"
                  >
                    <Clock className="h-4 w-4 text-amber-400" />
                    Redirect Time (seconds)
                  </Label>
                  <Input
                    id="triggerTime"
                    type="number"
                    min={1}
                    required
                    value={triggerTime}
                    onChange={(e) => {
                      setTriggerTime(Number(e.target.value));
                      setGenerated(false);
                    }}
                    className="bg-background/50 max-w-[140px]"
                  />
                  <p className="text-xs text-muted-foreground">
                    When to redirect (in seconds from video start)
                  </p>
                </div>

                {error && (
                  <p className="text-sm text-destructive">{error}</p>
                )}

                <Button
                  type="submit"
                  className="w-full rounded-full bg-primary hover:bg-primary/90 text-primary-foreground font-medium shadow-lg shadow-primary/20 h-11"
                >
                  Generate Page
                </Button>
              </form>
            </CardContent>
          </Card>
        </motion.div>

        {generated && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mt-6"
          >
            <Card className="bg-card/60 backdrop-blur-sm border-green-500/30">
              <CardContent className="pt-6">
                <div className="flex items-center gap-2 mb-4">
                  <CheckCircle className="h-5 w-5 text-green-500" />
                  <h3 className="font-semibold text-green-400">
                    Page Generated Successfully!
                  </h3>
                </div>

                <div className="bg-background/40 rounded-lg p-4 space-y-2 text-sm mb-5">
                  <p>
                    <span className="text-muted-foreground">Video:</span>{" "}
                    <span className="text-foreground break-all">
                      {youtubeUrl}
                    </span>
                  </p>
                  <p>
                    <span className="text-muted-foreground">Redirect:</span>{" "}
                    <span className="text-foreground break-all">
                      {redirectUrl}
                    </span>
                  </p>
                  <p>
                    <span className="text-muted-foreground">Trigger Time:</span>{" "}
                    <span className="text-foreground">{triggerTime} seconds</span>
                  </p>
                </div>

                <Button
                  onClick={handleDownload}
                  className="w-full rounded-full bg-green-600 hover:bg-green-700 text-white font-medium h-11"
                >
                  <Download className="mr-2 h-4 w-4" />
                  Download ZIP File
                </Button>
              </CardContent>
            </Card>
          </motion.div>
        )}
      </div>
    </main>
  );
}
