import React from "react";
import { motion } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { CmsContent } from "@shared/schema";
import { Music, Video } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

// Define the AI creation types
interface AICreation {
  title: string;
  description: string;
  type: "video" | "music";
  thumbnailUrl: string;
  link: string;
}

const FunAISection = () => {
  const { data: cmsContents } = useQuery<CmsContent[]>({
    queryKey: ["/api/cms"],
  });

  // Filter content for this section
  const funAiContent = React.useMemo(() => {
    if (!cmsContents) return {};
    
    return cmsContents
      .filter(content => content.section === "fun_ai")
      .reduce((acc, content) => {
        acc[content.key] = content.value;
        return acc;
      }, {} as Record<string, string>);
  }, [cmsContents]);

  // Example AI creations - these would normally come from your CMS or API
  const aiCreations: AICreation[] = [
    {
      title: "AI Generated Music: Summer Vibes",
      description: "An upbeat electronic track created with AI music generation tools.",
      type: "music",
      thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=80",
      link: "https://soundcloud.com/your-username/summer-vibes"
    },
    {
      title: "AI Video: Mountain Journey",
      description: "A mesmerizing journey through mountains and landscapes, generated entirely by AI.",
      type: "video",
      thumbnailUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=80",
      link: "https://youtube.com/watch?v=example1"
    },
    {
      title: "AI Composition: Rainy Day",
      description: "A peaceful piano composition created using AI composition techniques.",
      type: "music",
      thumbnailUrl: "https://images.unsplash.com/photo-1534224039826-c7a0eda0e6b3?ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=80",
      link: "https://soundcloud.com/your-username/rainy-day"
    },
    {
      title: "AI Video: Abstract Art in Motion",
      description: "A mesmerizing visualization of abstract patterns and shapes generated by AI.",
      type: "video",
      thumbnailUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=80",
      link: "https://youtube.com/watch?v=example2"
    }
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.5,
      },
    },
  };

  return (
    <section id="fun-ai" className="py-16 md:py-24 bg-gradient-to-b from-slate-50 to-slate-100 dark:from-gray-900 dark:to-gray-950">
      <div className="container px-4 md:px-6">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={containerVariants}
          className="flex flex-col items-center text-center mb-12"
        >
          <motion.h2 variants={itemVariants} className="text-3xl md:text-4xl font-bold tracking-tight mb-4">
            {funAiContent.title || "AI Creative Showcase"}
          </motion.h2>
          
          <motion.p variants={itemVariants} className="text-gray-500 dark:text-gray-400 max-w-[800px] mb-6">
            {funAiContent.subtitle || "Check out these fun AI-generated videos and music I've created"}
          </motion.p>
          
          <motion.p variants={itemVariants} className="text-gray-600 dark:text-gray-300 max-w-[800px] mb-12">
            {funAiContent.description || 
              "While my professional work focuses on marketing technology, I also enjoy exploring the creative possibilities of AI. Here are some of my experiments with AI-generated content."}
          </motion.p>
        </motion.div>

        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={containerVariants}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {aiCreations.map((creation, index) => (
            <motion.div key={index} variants={itemVariants}>
              <Card className="overflow-hidden h-full hover:shadow-lg transition-shadow duration-300">
                <div 
                  className="h-48 w-full relative bg-cover bg-center" 
                  style={{ backgroundImage: `url(${creation.thumbnailUrl})` }}
                >
                  <div className="absolute inset-0 bg-black bg-opacity-30 flex items-center justify-center">
                    <div className="rounded-full bg-primary/90 p-3 text-white">
                      {creation.type === "video" ? <Video size={24} /> : <Music size={24} />}
                    </div>
                  </div>
                </div>
                <CardContent className="p-5">
                  <h3 className="text-lg font-semibold mb-2">{creation.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300 text-sm mb-4">{creation.description}</p>
                  <a 
                    href={creation.link} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="block"
                  >
                    <Button variant="outline" className="w-full">
                      {creation.type === "video" ? "Watch Video" : "Listen to Track"}
                    </Button>
                  </a>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default FunAISection;